In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('mlflow_results.csv')
df.head()

,experiment,run_id,run_name,balanced_accuracy,roc_auc,precision,recall,recall_score,accuracy_score,precision_score,cohen_kappa,example_count,matthews_corrcoef,score,f1_score,log_loss,f1
0,Random_Forest_Classifier,91784ba1e74b477a840e0dcfa30823c4,RFC_with_None_n_False_bootstrap_n_matthews_cor...,0.565744,0.971807,0.839191,0.869513,0.869513,0.869513,0.839191,0.769554,69624.0,0.773717,0.869513,0.849241,0.328469,NaN
1,Random_Forest_Classifier,822665ebe1ce4c5da8668376b9bb35a2,RFC_with_None_n_False_bootstrap_n_cohen_kappa,0.570161,0.973328,0.841938,0.871266,0.871266,0.871266,0.841938,0.773060,69624.0,0.776872,0.871266,0.851999,0.320673,NaN
2,Random_Forest_Classifier,ec1016308f3d459e9b60ecd797765afb,RFC_with_None_n_False_bootstrap_n_precision,0.578782,0.974457,0.855718,0.872659,0.872659,0.872659,0.855718,0.775939,69624.0,0.779414,0.872659,0.854864,0.313497,NaN
3,Random_Forest_Classifier,a49e201d0c1e4ed89abb91bb757f1aa2,RFC_with_None_n_False_bootstrap_n_recall,0.555021,0.969159,0.833853,0.865994,0.865994,0.865994,0.833853,0.762103,69624.0,0.767661,0.865994,0.842435,0.342883,NaN
4,Random_Forest_Classifier,2cad9ada16ab4a7c995d4b5c104f78cf,RFC_with_None_n_False_bootstrap_n_f1,0.554782,0.969502,0.833824,0.866023,0.866023,0.866023,0.833824,0.762048,69624.0,0.767648,0.866023,0.842380,0.341200,NaN

In [ ]:
df.shape    # Размер нашей таблицы

(89, 17)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   experiment         89 non-null     object
 1   run_id             89 non-null     object
 2   run_name           89 non-null     object
 3   balanced_accuracy  89 non-null     float64
 4   roc_auc            72 non-null     float64
 5   precision          89 non-null     float64
 6   recall             89 non-null     float64
 7   recall_score       72 non-null     float64
 8   accuracy_score     72 non-null     float64
 9   precision_score    72 non-null     float64
 10  cohen_kappa        89 non-null     float64
 11  example_count      72 non-null     float64
 12  matthews_corrcoef  89 non-null     float64
 13  score              72 non-null     float64
 14  f1_score           78 non-null     float64
 15  log_loss           72 non-null     float64
 16  f1                 11 non-null     float64
dtypes: float64(14), object(3)
memory usage: 11.9+ KB

Уберем SVC, так как он очень медленный, а также обучался не на всей выборке

In [ ]:
df = df[df['experiment'] != 'SVC']
df.shape

(86, 17)

Унификация столбцов с метрикой F1. В разных экспериментах MLflow сохранял F1-score то в столбце f1, то в f1_score. Этот код объединяет оба столбца в один f1, беря значение из любого непустого источника

In [8]:
df['f1'] = df['f1'].combine_first(df['f1_score'])
df['f1'].isnull().sum()

np.int64(0)

Удаляем ненужные или повторяющиеся столбцы, а также выводим таблицу полностью

In [9]:
df = df.drop(columns=['experiment', 'run_id', 'recall_score', 'accuracy_score', \
                      'precision_score', 'example_count', 'score', 'log_loss', 'f1_score'])

with pd.option_context('display.max_rows', None):
    display(df)

,run_name,balanced_accuracy,roc_auc,precision,recall,cohen_kappa,matthews_corrcoef,f1
0,RFC_with_None_n_False_bootstrap_n_matthews_cor...,0.565744,0.971807,0.839191,0.869513,0.769554,0.773717,0.849241
1,RFC_with_None_n_False_bootstrap_n_cohen_kappa,0.570161,0.973328,0.841938,0.871266,0.773060,0.776872,0.851999
2,RFC_with_None_n_False_bootstrap_n_precision,0.578782,0.974457,0.855718,0.872659,0.775939,0.779414,0.854864
3,RFC_with_None_n_False_bootstrap_n_recall,0.555021,0.969159,0.833853,0.865994,0.762103,0.767661,0.842435
4,RFC_with_None_n_False_bootstrap_n_f1,0.554782,0.969502,0.833824,0.866023,0.762048,0.767648,0.842380
5,RFC_with_None_n_False_bootstrap_n_balanced_acc...,0.571145,0.973596,0.856342,0.871079,0.772855,0.776510,0.852166
6,RFC_with_None_n_True_bootstrap_n_matthews_corr...,0.571833,0.973476,0.842734,0.871653,0.773943,0.777591,0.852833
7,RFC_with_None_n_True_bootstrap_n_cohen_kappa,0.565343,0.971548,0.838824,0.869255,0.769112,0.773278,0.848930
8,RFC_with_None_n_True_bootstrap_n_precision,0.593189,0.975319,0.860303,0.875560,0.781742,0.784611,0.860125
9,RFC_with_None_n_True_bootstrap_n_recall,0.539519,0.966224,0.827047,0.862404,0.753230,0.761255,0.833074
10,RFC_with_None_n_True_bootstrap_n_f1,0.538632,0.966225,0.827198,0.862260,0.752825,0.761127,0.832384
11,RFC_with_None_n_True_bootstrap_n_balanced_accu...,0.579951,0.974776,0.856233,0.872659,0.776036,0.779441,0.855108
12,RFC_with_log2_n_False_bootstrap_n_matthews_cor...,0.596914,0.975522,0.861337,0.875905,0.782518,0.785280,0.860988
13,RFC_with_log2_n_False_bootstrap_n_cohen_kappa,0.574878,0.974030,0.855167,0.871495,0.773671,0.777315,0.853016
14,RFC_with_log2_n_False_bootstrap_n_precision,0.569654,0.973855,0.860506,0.870605,0.771913,0.775690,0.851354
15,RFC_with_log2_n_False_bootstrap_n_recall,0.593439,0.976094,0.860584,0.875704,0.782040,0.784898,0.860314
16,RFC_with_log2_n_False_bootstrap_n_f1,0.586830,0.974034,0.857534,0.873722,0.778208,0.781362,0.857256
17,RFC_with_log2_n_False_bootstrap_n_balanced_acc...,0.570707,0.973748,0.841513,0.870734,0.772297,0.775901,0.851871
18,RFC_with_log2_n_True_bootstrap_n_matthews_corr...,0.599775,0.975515,0.860275,0.875316,0.781485,0.784209,0.860737
19,RFC_with_log2_n_True_bootstrap_n_cohen_kappa,0.579330,0.974093,0.858082,0.873449,0.777325,0.780796,0.855670
20,RFC_with_log2_n_True_bootstrap_n_precision,0.581136,0.975053,0.859121,0.873794,0.778168,0.781431,0.856515
21,RFC_with_log2_n_True_bootstrap_n_recall,0.565791,0.971783,0.839411,0.869729,0.769904,0.774108,0.849388
22,RFC_with_log2_n_True_bootstrap_n_f1,0.568874,0.972502,0.841366,0.870921,0.772278,0.776264,0.851258
23,RFC_with_log2_n_True_bootstrap_n_balanced_accu...,0.566166,0.972337,0.839216,0.869442,0.769523,0.773594,0.849368
24,RFC_with_sqrt_n_False_bootstrap_n_matthews_cor...,0.564659,0.972007,0.838356,0.868953,0.768500,0.772716,0.848480
25,RFC_with_sqrt_n_False_bootstrap_n_cohen_kappa,0.576864,0.973764,0.856015,0.872630,0.775766,0.779335,0.854467
26,RFC_with_sqrt_n_False_bootstrap_n_precision,0.579257,0.974025,0.856068,0.872702,0.776027,0.779470,0.855000
27,RFC_with_sqrt_n_False_bootstrap_n_recall,0.569120,0.973045,0.860034,0.870275,0.771333,0.775109,0.850967
28,RFC_with_sqrt_n_False_bootstrap_n_f1,0.591985,0.975740,0.859696,0.875101,0.780790,0.783765,0.859376
29,RFC_with_sqrt_n_False_bootstrap_n_balanced_acc...,0.582387,0.974913,0.855774,0.873032,0.776812,0.780074,0.855970
30,RFC_with_sqrt_n_True_bootstrap_n_matthews_corr...,0.575108,0.973529,0.855208,0.871855,0.774372,0.777939,0.853518
31,RFC_with_sqrt_n_True_bootstrap_n_cohen_kappa,0.575166,0.973230,0.854714,0.871567,0.773975,0.777452,0.853390
32,RFC_with_sqrt_n_True_bootstrap_n_precision,0.581973,0.974486,0.855917,0.872874,0.776188,0.779744,0.855275
33,RFC_with_sqrt_n_True_bootstrap_n_recall,0.584290,0.974651,0.858178,0.873420,0.777517,0.780750,0.856528
34,RFC_with_sqrt_n_True_bootstrap_n_f1,0.575272,0.973508,0.855271,0.871912,0.774355,0.778008,0.853454
35,RFC_with_sqrt_n_True_bootstrap_n_balanced_accu...,0.593561,0.976068,0.860872,0.875761,0.782081,0.784973,0.860310
36,DTC_with_random_n_gini_n_matthews_corrcoef,0.589794,0.965578,0.845176,0.864616,0.762326,0.765257,0.849028
37,DTC_with_random_n_gini_n_cohen_kappa,0.570622,0.965358,0.836325,0.864199,0.762722,0.765251,0.847635
38,DTC_with_random_n_gini_n_precision,0.600807,0.970324,0.849430,0.864817,0.764795,0.766336,0.853188
39,DTC_with_random_n_gini_n_recall,0.571035,0.944263,0.831712,0.851775,0.743400,0.744061,0.841534
40,DTC_with_random_n_gini_n_f1,0.584496,0.965663,0.845602,0.864960,0.762822,0.765824,0.848774
41,DTC_with_random_n_gini_n_balanced_accuracy,0.588471,0.967000,0.849603,0.867244,0.767729,0.770275,0.852311
42,DTC_with_best_n_gini_n_matthews_corrcoef,0.599297,0.967047,0.852470,0.867459,0.769466,0.771329,0.855010
43,DTC_with_best_n_gini_n_cohen_kappa,0.588439,0.966972,0.849285,0.866727,0.767024,0.769563,0.851889
44,DTC_with_best_n_gini_n_precision,0.599074,0.969558,0.854569,0.870533,0.773960,0.776284,0.856912
45,DTC_with_best_n_gini_n_recall,0.600746,0.961717,0.847120,0.861125,0.759449,0.760797,0.850409
46,DTC_with_best_n_gini_n_f1,0.588823,0.966781,0.849518,0.866856,0.767299,0.769812,0.852107
47,DTC_with_best_n_gini_n_balanced_accuracy,0.600053,0.967574,0.854049,0.869355,0.772430,0.774455,0.856508
48,DTC_with_random_n_entropy_n_matthews_corrcoef,0.594743,0.967517,0.847164,0.864946,0.763725,0.765925,0.851290
49,DTC_with_random_n_entropy_n_cohen_kappa,0.574543,0.968680,0.838027,0.864472,0.763803,0.765669,0.849533
50,DTC_with_random_n_entropy_n_precision,0.572967,0.964008,0.838056,0.865391,0.764988,0.767433,0.849201
51,DTC_with_random_n_entropy_n_recall,0.571119,0.959759,0.834130,0.860551,0.757373,0.759441,0.845350
52,DTC_with_random_n_entropy_n_f1,0.581665,0.965364,0.845567,0.865047,0.762958,0.766078,0.848396
53,DTC_with_random_n_entropy_n_balanced_accuracy,0.600264,0.969643,0.854128,0.869542,0.772549,0.774494,0.856770
54,DTC_with_best_n_entropy_n_matthews_corrcoef,0.586179,0.965458,0.846626,0.865851,0.764212,0.767447,0.849342
55,DTC_with_best_n_entropy_n_cohen_kappa,0.585884,0.965521,0.847018,0.865793,0.764261,0.767392,0.849439
56,DTC_with_best_n_entropy_n_precision,0.592698,0.968887,0.850612,0.867862,0.768828,0.771101,0.853768
57,DTC_with_best_n_entropy_n_recall,0.581083,0.965445,0.845635,0.865348,0.763287,0.766546,0.848375
58,DTC_with_best_n_entropy_n_f1,0.587071,0.965492,0.847129,0.866109,0.764780,0.767938,0.849828
59,DTC_with_best_n_entropy_n_balanced_accuracy,0.593475,0.968290,0.853686,0.870318,0.773354,0.775855,0.855898
60,DTC_with_random_n_gini_n_matthews_corrcoef,0.582671,0.966396,0.847907,0.867431,0.766828,0.770188,0.850376
61,DTC_with_random_n_gini_n_cohen_kappa,0.571035,0.944263,0.831712,0.851775,0.743400,0.744061,0.841534
62,DTC_with_random_n_gini_n_precision,0.562151,0.963272,0.832442,0.863165,0.759164,0.762709,0.843735
63,DTC_with_random_n_gini_n_recall,0.571035,0.944263,0.831712,0.851775,0.743400,0.744061,0.841534
64,DTC_with_random_n_gini_n_f1,0.586394,0.952169,0.840749,0.855423,0.752034,0.752398,0.847993
65,DTC_with_random_n_gini_n_balanced_accuracy,0.597894,0.969390,0.851621,0.866454,0.767801,0.769357,0.854503
66,DTC_with_best_n_gini_n_matthews_corrcoef,0.594949,0.968529,0.850704,0.866813,0.767735,0.769607,0.853822
67,DTC_with_best_n_gini_n_cohen_kappa,0.597791,0.967011,0.851488,0.866842,0.768254,0.770175,0.854135
68,DTC_with_best_n_gini_n_precision,0.601967,0.969438,0.850234,0.865348,0.765834,0.767334,0.853903
69,DTC_with_best_n_gini_n_recall,0.595820,0.961939,0.847862,0.862648,0.761477,0.763171,0.850546
70,DTC_with_best_n_gini_n_f1,0.588872,0.966714,0.849536,0.866856,0.767309,0.769816,0.852124
71,DTC_with_best_n_gini_n_balanced_accuracy,0.593481,0.969556,0.852172,0.868508,0.770427,0.772480,0.854945
72,LR_with_f1_metric,0.746731,NaN,0.842895,0.811574,0.686474,0.689655,0.821417
73,LR_with_recall_metric,0.551391,NaN,0.812882,0.849693,0.729278,0.738124,0.819830
74,LR_with_precision_metric,0.745100,NaN,0.841865,0.811545,0.685978,0.689164,0.820878
75,LR_with_balanced_accuracy_metric,0.745406,NaN,0.841969,0.811502,0.685907,0.689130,0.820854
76,LR_with_f1_metric,0.743731,NaN,0.841522,0.812162,0.686514,0.689751,0.820963
77,LR_with_recall_metric,0.545475,NaN,0.809980,0.849161,0.726904,0.737620,0.815110
78,LR_with_precision_metric,0.746611,NaN,0.843108,0.812636,0.687889,0.691070,0.822069
79,LR_with_balanced_accuracy_metric,0.749157,NaN,0.844232,0.810295,0.685312,0.688610,0.821289
83,XGBoost_with_gbtree_booster_n_matthews_corrcoe...,0.615490,NaN,0.863263,0.876422,0.784608,0.786523,0.864623
84,XGBoost_with_gbtree_booster_n_cohen_kappa_metric,0.506552,NaN,0.849153,0.852953,0.730172,0.746531,0.805338
85,XGBoost_with_gbtree_booster_n_precision_metric,0.560893,NaN,0.854591,0.870217,0.767981,0.775465,0.844583
86,XGBoost_with_gbtree_booster_n_recall_metric,0.548587,NaN,0.845912,0.863567,0.756854,0.763686,0.837344
87,XGBoost_with_gbtree_booster_n_f1_metric,0.489535,NaN,0.861805,0.844522,0.711563,0.732030,0.787792
88,XGBoost_with_gbtree_booster_n_balanced_accurac...,0.614481,NaN,0.861799,0.875417,0.783002,0.784789,0.863875

Пропуски значений метрик, которые мы не логировали у некоторых моделей, заполняем нулями

In [11]:
df = df.fillna(0)
df.isnull().sum()

run_name             0
balanced_accuracy    0
roc_auc              0
precision            0
recall               0
cohen_kappa          0
matthews_corrcoef    0
f1                   0
dtype: int64

Выбираем 4 важные метрики, нормализуем их, прописываем кастомный словарь весов важности метрик, суммируем произведение веса на нормализованную величину метрики. Выводим топ-10 самых лучших результатов новой кастомной метрики - composite_score

In [12]:
important_metrics = ['f1', 'roc_auc', 'precision', 'recall']

df_norm = df[important_metrics].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

weights_of_metrics = {
    'f1': 0.4,
    'roc_auc': 0.3,
    'precision': 0.15,
    'recall': 0.15
}

df['composite_score'] = sum(df_norm[metric] * weight for metric, weight in weights_of_metrics.items())

df = df.sort_values('composite_score', ascending=False)
df.head(10)

,run_name,balanced_accuracy,roc_auc,precision,recall,cohen_kappa,matthews_corrcoef,f1,composite_score
12,RFC_with_log2_n_False_bootstrap_n_matthews_cor...,0.596914,0.975522,0.861337,0.875905,0.782518,0.785280,0.860988,0.974308
35,RFC_with_sqrt_n_True_bootstrap_n_balanced_accu...,0.593561,0.976068,0.860872,0.875761,0.782081,0.784973,0.860310,0.969308
18,RFC_with_log2_n_True_bootstrap_n_matthews_corr...,0.599775,0.975515,0.860275,0.875316,0.781485,0.784209,0.860737,0.968670
15,RFC_with_log2_n_False_bootstrap_n_recall,0.593439,0.976094,0.860584,0.875704,0.782040,0.784898,0.860314,0.968396
8,RFC_with_None_n_True_bootstrap_n_precision,0.593189,0.975319,0.860303,0.875560,0.781742,0.784611,0.860125,0.966055
28,RFC_with_sqrt_n_False_bootstrap_n_f1,0.591985,0.975740,0.859696,0.875101,0.780790,0.783765,0.859376,0.959535
20,RFC_with_log2_n_True_bootstrap_n_precision,0.581136,0.975053,0.859121,0.873794,0.778168,0.781431,0.856515,0.939849
16,RFC_with_log2_n_False_bootstrap_n_f1,0.586830,0.974034,0.857534,0.873722,0.778208,0.781362,0.857256,0.938763
33,RFC_with_sqrt_n_True_bootstrap_n_recall,0.584290,0.974651,0.858178,0.873420,0.777517,0.780750,0.856528,0.936288
19,RFC_with_log2_n_True_bootstrap_n_cohen_kappa,0.579330,0.974093,0.858082,0.873449,0.777325,0.780796,0.855670,0.931447

Это называется тотальная доминация Random Forest. Просто весь топ-10 - это одни леса...
Самая лучшая модель - Random Forest с max_features='log2', bootstrap=False и улучшаемой метрикой - matthews_corrcoef.
Напишем еще раз код конкретно для этой модели, но еще подкрутим гиперпараметры. Если n_trials=20 - это было для всех моделей, то для самой лучшей будем использовать количество испытаний равным 30, что должно улучшить модель