In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('clear_data.csv', sep=';', decimal=',')
df.head()

   type  algo_2021  chl_2021  cvet_2021  mut_2021     T_2021
0     0   0.857437  0.138596   0.921551  0.357980  18.442838
1     1   0.759559  0.107960   0.932768  0.353177  19.725651
2     2   0.620076  0.240855   0.873727  0.375476  20.962448
3     2   0.620013  0.237161   0.876461  0.374729  21.063968
4     3   0.642732  0.252866   0.865378  0.377850  21.186324

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351631 entries, 0 to 351630
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   type       351631 non-null  int64
 1   algo_2021  351631 non-null  float64
 2   chl_2021   351631 non-null  float64
 3   cvet_2021  351631 non-null  float64
 4   mut_2021   351631 non-null  float64
 5   T_2021     351631 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 16.1 MB

In [5]:
cols = [col for col in df.columns if df[col].dtype == 'object']
df[cols] = df[cols].replace(',', '.', regex=True).astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351631 entries, 0 to 351630
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   type       351631 non-null  int64
 1   algo_2021  351631 non-null  float64
 2   chl_2021   351631 non-null  float64
 3   cvet_2021  351631 non-null  float64
 4   mut_2021   351631 non-null  float64
 5   T_2021     351631 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 16.1 MB

In [6]:
df.shape

(351631, 6)

In [7]:
df.describe()

,type,algo_2021,chl_2021,cvet_2021,mut_2021,T_2021
count,351631.000000,351631.000000,351631.000000,351631.000000,351631.000000,351631.000000
mean,1.746976,0.729918,0.208316,0.902214,0.368464,24.221831
std,0.674797,0.138899,0.044135,0.029512,0.008149,2.156989
min,0.000000,0.570932,-0.376229,0.844685,0.292459,18.442838
25%,1.000000,0.620428,0.196195,0.880782,0.364494,23.196112
50%,2.000000,0.631152,0.225934,0.889040,0.372002,23.568897
75%,2.000000,0.872518,0.233372,0.923354,0.373759,24.494045
max,3.000000,1.078056,0.278832,1.197751,0.382777,42.230621

In [10]:
df['type'].value_counts()

type
2    189458
1    115345
3     40010
0      6818
Name: count, dtype: int64